[[redirects]]
from = "/writing-tests-first/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/wcag-em/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/vite/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/twitch-plays-dinosaur-game/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/testing-mobile-accessibility/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/terrible-web-components/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/tabs-react/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/svg-accessibility/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/style-stage/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/stream-schedule-with-eleventy/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/specs-tests-and-mocks/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/september-2021-ama/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/remix/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/redwoodjs-docs/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/react-three-accessibility/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/react-dialogs/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/progressively-enhanced-rating/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/prismic/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/postgresql/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/polypane/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/personalizing-for-accessibility/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/jammin-out-with-web-audio/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/github-navigation/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/getting-started-automated/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/generative-avatars/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/gaad-ask-me-anything/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/first-look-eleventy-serverless/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/fashion/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/elm/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/eleventy-custom-extensions/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/elementor/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/diving-into-wcag/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/disabling-buttons/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/deno-oak-apis/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/debugging-semantics/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/dang-spicy-web-components/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/cypress/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/build-your-own-design-system/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/build-ui-with-figma/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/auditing-accessibility/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/ask-me-anything/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessible-todo-app/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessible-svgs-react/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessible-social-content/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessible-routing-in-redwoodjs/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessible-forms/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessible-design-systems/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/accessibility-tree/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/a11ysurf/calendar"
to = "/.netlify/functions/calendar"
status = 200
force = true
_generated_by_eleventy_serverless = "calendar"

[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/playlist?list=PLZluKlEc91YzYor_ItAax4d2iXTXbFAFF"
status = 301
force = true
